blueprint:
  name: DF setting BP test
  description: Turn a toggle on based on another toggle turning on
  domain: automation
  input:
    df_event_status_input:
      name: DF event status
      selector:
        entity:
          domain: input_boolean
    set_df_conditions_input:
      name: Set DF conditions
      selector:
        entity:
          domain: input_boolean

trigger:
  - platform: state
    entity_id: !input df_event_status_input
condition: []
action:
  - action: |
      {% if trigger.to_state.state == "on" %}
        input_boolean.turn_on
      {% else %}
        input_boolean.turn_off
      {% endif %}
    target:
      entity_id: !input set_df_conditions_input
