blueprint:
  name: Test BP Import
  description: Testing MP
  domain: automation
  input:
    calendar_df_weh:
      name: Calendar DF WEH
      description: "The calendar entity that triggers DF events"
      selector:
        entity:
          filter:
            - domain: calendar
variables: 
  calendar_df_weh: !input calendar_df_weh
trigger:
  - platform: state
    entity_id: !input calendar_df_weh
    from: "off"
    to: "on"
    id: start_df_event
    alias: Calendar event for DF turns on
action:
  - variables:
      t_delta: |-
        {% if is_state('calendar_df_weh', 'on') %}
          {{ float((state_attr('calendar_df_weh', 'description') | from_json)['T_delta'], 0)  }}
        {% else %}
          0
        {% endif %}
      season: |-
        {% if is_state('calendar_df_weh', 'on') %}
          {{ (state_attr('calendar_df_weh', 'description') | from_json)['season']  }}
        {% else %}
          {{ '' }}
        {% endif %}
      df_delta_multiplier: |-
        {% if is_state('calendar_df_weh', 'on') %}
          {% if (state_attr('calendar_df_weh', 'description') | from_json)['season'] == 'cooling' %}
            {{ float(1, 0) }}
          {% elif (state_attr('calendar_df_weh', 'description') | from_json)['season'] == 'heating' %} 
            {{ float(-1, 0) }}
          {% else %}
              0
          {% endif %}
        {% endif %}
    alias: test action bp import