blueprint:
  name: Test BP Import ACTION
  description: Testing MP
  source_url: https://github.com/Maharshi-Pathak/HA-notes/blob/main/test_df_bp.yaml
  author: Maharshi Pathak - Northeastern University
  domain: automation
  input:
    calendar_df_weh:
      name: Calendar DF WEH
      description: "The calendar entity that triggers DF events"
      selector:
        entity:
          filter:
            - domain: calendar
    notify_entity: 
      name: notify_entity
      description: Notification
      selector: 
        entitiy:
          filter:
            - domain: notify

trigger:
  - platform: state
    entity_id: !input calendar_df_weh
    from: "off"
    to: "on"
    id: start_df_event
    alias: Calendar event for DF turns on

action:
  - action: !input notify_entity
    metadata: {}
    data:
      title: "WEH MPN DF AUTO TEST NOTIFICATION"
      message: "THIS IS A TEST"
  # - variables:
  #     calendar_df_weh: !input calendar_df_weh
  
    #   t_delta: >-
    #     {% if is_state('calendar_df_weh', 'on') %}
    #       {{ float((state_attr('calendar_df_weh', 'description') | from_json)['T_delta'], 0)  }}
    #     {% else %}
    #       0
    #     {% endif %}
    #   season: >-
    #     {% if is_state('calendar_df_weh', 'on') %}
    #       {{ (state_attr('calendar_df_weh', 'description') | from_json)['season']  }}
    #     {% else %}
    #       {{ '' }}
    #     {% endif %}
    #   df_delta_multiplier: >-
    #     {% if is_state('calendar_df_weh', 'on') %}
    #       {% if (state_attr('calendar_df_weh', 'description') | from_json)['season'] == 'cooling' %}
    #         {{ float(1, 0) }}
    #       {% elif (state_attr('calendar_df_weh', 'description') | from_json)['season'] == 'heating' %} 
    #         {{ float(-1, 0) }}
    #       {% else %}
    #           0
    #       {% endif %}
    #     {% endif %}
    # alias: test action bp import